### ISSUE TITLE
raised unexpected: ValueError("Invalid isoformat string: '-'")

### ISSUE THREAD

**Issue by ilyakatz** [ilyakatz/dividend_chaser#45]
13:08:12 worker.1 | [2020-01-18 13:08:12,603: WARNING/ForkPoolWorker-1] Running worker for ['AIW', 'AIZ', 'AIZP', 'AJG', 'AJX']
13:08:12 worker.1 | [2020-01-18 13:08:12,790: INFO/MainProcess] Received task: tasks.reload_batch_worker[54e7792d-7dbc-46a2-b27c-34fc4b201b66]  
13:09:32 worker.1 | [2020-01-18 13:09:32,172: ERROR/ForkPoolWorker-1] Task tasks.reload_batch_worker[40cff764-72b6-4c88-9e11-6569be3b851a] raised unexpected: ValueError("Invalid isoformat string: '-'")
13:09:32 worker.1 | Traceback (most recent call last):
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividends_env/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
13:09:32 worker.1 |     R = retval = fun(*args, **kwargs)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividends_env/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
13:09:32 worker.1 |     return self.run(*args, **kwargs)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/tasks.py", line 23, in reload_batch_worker
13:09:32 worker.1 |     DividendHistory(stocks).dump()
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/workers/dividend_history.py", line 92, in dump
13:09:32 worker.1 |     # json.dump(self.dividends_data, fp)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/workers/dividend_history.py", line 109, in _enrich
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/workers/dividend_history.py", line 135, in _enrich_with_next_dividend
13:09:32 worker.1 |     self.dividends_data[symbol]["next_dividend"] = service.next_dividend(symbol)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/services/base_data_service.py", line 17, in calculate_next_dividend
13:09:32 worker.1 |     next_dividend_dates = self._calculate_next_dividend(self.symbols)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/services/yahoo_data_service.py", line 99, in _calculate_next_dividend
13:09:32 worker.1 |     dividends = self._next_div(data, symbol)
13:09:32 worker.1 |   File "/Users/ilyakatz/ws/dividend_chaser/dividend_chaser/services/base_data_service.py", line 37, in _next_div
13:09:32 worker.1 |     next_div_date = datetime.date.fromisoformat(date_str)
13:09:32 worker.1 | ValueError: Invalid isoformat string: '-'

**Comment by ilyakatz** [comment]
fixed via #46
